# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js 20
      uses: actions/setup-node@v4
    - name: Install dependencies 
      run: npm install

  test-start:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm install
    - name: Start app
      run: npm run start
    - name: Execute integration tests
      run: npm run test